const titles = [
{ name: "Voidwalker", rarity: "Legendary", color: "violet", prob: 0.97, aura: true },
{ name: "Shadowling", rarity: "Epic", color: "#9900ff", prob: 0.9, aura: true },
{ name: "Drifter", rarity: "Rare", color: "#4444ff", prob: 0.75, aura: true },
{ name: "Pulsebound", rarity: "Uncommon", color: "#66ccff", prob: 0.6, aura: true },
{ name: "Neon Rookie", rarity: "Common", color: "#cccccc", prob: 0.4, aura: true },
  { name: "skibidi", rarity: "Common", color: "#cccccc", prob: 0.3, aura: true },  
  { name: "ohio", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true },
    { name: "drpepper", rarity: "Common", color: "#22ff00", prob: 0.4, aura: true },
    { name: "ppp", rarity: "Common", color: "#22ff00", prob: 0.5, aura: true },
    { name: "ijkjkjk", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true },
{ name: "tung tung tung sahur", rarity: "Legendary", color: "violet", prob: 0.97, aura: true },
{ name: "baby gronk", rarity: "Epic", color: "#9900ff", prob: 0.9, aura: true },
{ name: "drifum", rarity: "Rare", color: "#4444ff", prob: 0.75 , aura: true},
{ name: "poopbound", rarity: "Uncommon", color: "#66ccff", prob: 0.6, aura: true },
{ name: "Neoop Rookie", rarity: "Common", color: "#cccccc", prob: 0.4, aura: true },
  { name: "white", rarity: "Common", color: "#cccccc", prob: 0.3, aura: true },  
  { name: "black", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true },
    { name: "error", rarity: "Common", color: "#22ff00", prob: 0.4, aura: true },
    { name: "pepsi", rarity: "Common", color: "#22ff00", prob: 0.5, aura: true },
    { name: "oop", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true },
{ name: "Voidwalker", rarity: "Legendary", color: "violet", prob: 0.97, aura: true },
{ name: "Shadowling", rarity: "Epic", color: "#9900ff", prob: 0.9, aura: true },
{ name: "Drifter", rarity: "Rare", color: "#4444ff", prob: 0.75, aura: true },
{ name: "halo reach RARE ASF", rarity: "Uncommon", color: "#66ccff", prob: 0.0000001 },
{ name: "Rookie", rarity: "Common", color: "#cccccc", prob: 0.4, aura: true },
  { name: "poop", rarity: "Common", color: "#cccccc", prob: 0.3, aura: true },  
  { name: "oh", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true }, 
    { name: "k", rarity: "Common", color: "#22ff00", prob: 0.4, aura: true },
    { name: "fortnite", rarity: "Common", color: "#22ff00", prob: 0.5, aura: true },
    { name: "yes", rarity: "Common", color: "#22ff00", prob: 0.1, aura: true },



// Repeat this pattern to fill up 50-100 titles with creative names, colors, and rarities
];
